apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
  # namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Argo CD HTML App</title>
    </head>
    <body>
      <h1>Hello from Argo CD ðŸš€</h1>
      <p>Deployment successful!</p>
    </body>
    </html>
